### ISSUE TITLE
use code4sa questions data

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1797]
From Greg:

> Our changes have been made. I suggest that MySociety retain the Questions feature as they currently show which MPs have asked questions. They can simply pull the questions directly from the PMG API and no longer need to scrape hansards at all. They can use an API like this one for each MP:
>
> https://api.pmg.org.za/member/519/questions/

And PMG:

> It allows searching per minister which is important. It does not show all empty questions, only those with replies. However, we much prefer this to having gaps in the replies. See Greg's comments below.

**Comment by paullenz** [comment]
As part of this we should look at making some of the changes referenced in: 

https://github.com/mysociety/pombola/issues/1492

 Show a list of "most recently answered questions" at the top of /questions
 Pagination for ministries with many questions
 A snippet of the question text to be included on the question list pages, more like: http://myreps.sailing360.co.za/questions
 Remove the next and previous ministries links (they're a lot of noise if there are only a couple of questions.
 There are some duplicate ministries on the questions list page - they should be merged
 Perhaps make it more obvious how to get back to the index of questions (at the moment the link in the breadcrumbs isn't very obvious)

My (Greg) additional suggestions:

 Inclusion of a 'most recently asked questions' view in addition to 'most recently answered questions'.
 Displaying the date that an answer was provided.
 Linking to source documents. This may be particularly useful for cases where the scraper is not able to parse the answer document (currently these answers are not imported). One option might be to use a DocumentCloud instance (possibly SourceAfrica) to embed the original document.
 Including a speakers party affiliation next to their question (requires addressing #1551).
 Not linking to a speaker if the link results in a 404 error (noted in #1551).
 Including a speaker's real name alongside their title (the President, Speaker, Leader of the Opposition, etc.) - also requires addressing #1551.
 Improving the formatting of answers. The plain text formatting of answers is much cleaner (and does a better job of maintaining tables) than the condensed version that we end up seeing. See #1561.

**Comment by geoffkilpin** [comment]
An update on the status of some of the improvements from #1492 noted by @paullenz above (changed in the #1562 and #1564 pull requests)

Mark's:
- [x] Show a list of "most recently answered questions" at the top of /questions
- [x] Pagination for ministries with many questions
- [x] A snippet of the question text to be included on the question list pages, more like: http://myreps.sailing360.co.za/questions
- [x] Remove the next and previous ministries links (they're a lot of noise if there are only a couple of questions.
- [ ] There are some duplicate ministries on the questions list page - they should be merged **(this was addressed but it appears a few more have appeared)**
- [ ] Perhaps make it more obvious how to get back to the index of questions (at the moment the link in the breadcrumbs isn't very obvious)

Me:

- [x] Inclusion of a 'most recently asked questions' view in addition to 'most recently answered questions'.
- [x] Displaying the date that an answer was provided.
- [x] Linking to source documents. This may be particularly useful for cases where the scraper is not able to parse the answer document (currently these answers are not imported). One option might be to use a [DocumentCloud](http://www.documentcloud.org/home) instance (possibly [SourceAfrica](http://sourceafrica.net/home)) to embed the original document. **(solution doesn't use SourceAfrica)**
- [ ] Including a speakers party affiliation next to their question (requires addressing #1551).
- [ ] Not linking to a speaker if the link results in a 404 error (noted in #1551).
- [ ] Including a speaker's real name alongside their title (the President, Speaker, Leader of the Opposition, etc.) - also requires addressing #1551.
- [x] Improving the formatting of answers. The plain text formatting of answers is much cleaner (and does a better job of maintaining tables) than the condensed version that we end up seeing. See #1561.

**Comment by JenMysoc** [comment]
PMG have brought this up as a high priority for them. 

The main issue seems to be that although we can pull in questions data, the answers data is not well matched. The only data that has been matched well is the manual import of data from 2008-2014 that was done when questions was launched. 

The questions and answers need to be shown both on the Questions section (http://www.pa.org.za/question) and secondarily they need to be linked to the MP profile for the person who responded to a question.
