### ISSUE TITLE
Refactor codebase for running multiple sites

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#750]
### Overview

A discussion needs to be had about the best way to reuse the pombola codebase across several sites with differing needs, including:

- different styling
- different translations of common strings
- different content in templates
- different feature sets (eg hansard, scorecards)
- different governmental structures (eg one rep per area, several reps per area, a mix of both, other)
- ease of installation and customisation
- ability to upgrade instance gradually (codebase may be allowed to lag behind master)
- ability to change sites for specific events (eg elections)
- ability for admins to alter some site settings
- documentation and communication of changes
- ability to add third party apps to a site

### Known specific issues:

- [ ] site specific styling should not be in `core/static/[sass|css]`
- [ ] South Africa has a custom [home.html](https://github.com/mysociety/pombola/blob/master/pombola/south_africa/templates/map/home.html) and [map-drilldown.js](https://github.com/mysociety/pombola/blob/master/pombola/south_africa/static/js/map-drilldown.js) - change should be integrated back into map app (see #741 for dev notes)
- [ ] Country specific config could be removed from the `general.yaml` file (see #613)
- [ ] Country specific config could be put into database (see #722)
- [ ] Various conditionals in the code (eg `if settings.COUNTRY_APP == 'foo':`) should be eliminated, no country specific behaviour should be in generic apps.
- [ ] Kenya specific hansard code should be extracted from the hansard app (or hansard app replaced with SayIt)
- [ ] some colours still hardcoded into CSS, or poorly named.
- [ ] i18n (work has started in #713 and `issues/713-...` topic branch)

### Possible approaches:

- Continue with site specific apps
- Some sort of theme approach
- Each site is a distinct Django project, with standard apps included from pypi modules
- something else...

**Comment by paullenz** [comment]
As we are not currently anticipating any new Pombola sites in the near-medium term I closing this ticket
